accounts/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views
from django.urls import reverse

app_name = 'accounts'
urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('register/', views.register, name='register'),
    path('register_profile/<str:user_type>/', views.register_profile, name='register_profile'),
    path('password_change/', auth_views.PasswordChangeView.as_view(success_url='/accounts/login/'), name='password_change'),
    path('password_reset/', views.password_reset_request, name='password_reset'),
    # path('password_reset/', auth_views.PasswordResetView.as_view(template_name='accounts/password/password_reset.html'), name='password_reset'),
    # path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='accounts/password/password_reset_done.html'), name='password_reset_done'),
    # path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password/password_reset_confirm.html'), name='password_reset_confirm'),
    # path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password/password_reset_complete.html'), name='password_reset_complete'), 
    path('profile/<int:user_id>', views.profile, name='profile'),
    path('', views.dashboard, name='dashboard'),
    path('working_shifts/edit/', views.edit_working_shifts, name='edit_working_shifts'),
    path('working_shifts/', views.view_working_shifts, name='view_working_shifts'),
    path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', views.activate, name='activate'),
    # path('', views.index),
]

appointments/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from .views import AppointmentDetailView

app_name = 'appointments'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/<int:doctor_id>', views.create, name='create_appointment'),
    path('edit/<int:appointment_id>', views.edit, name='edit_appointment'),
    path('doctors/', views.doctors, name='list_doctors'),
    path('doctor-availability/', views.doctor_availability, name='doctor_availability'),
    path('approve-status/<int:pk>', views.set_approval_status, name='set_approval_status'),
    path('details/<int:pk>', AppointmentDetailView.as_view(), name='view_details'),
    path('delete/<int:appointment_id>', views.delete, name='delete_appointment'),
    path('cancel/<int:appointment_id>', views.cancel_appointment, name='cancel_appointment'),
]

hospsys/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('appointments/', include('appointments.urls')),
    path('video_chat/', include('video_chat.urls')),
    path("__reload__/", include("django_browser_reload.urls")),
     path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='accounts/password/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password/password_reset_confirm.html'), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password/password_reset_complete.html'), name='password_reset_complete'), 

]

video_chat/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'video_chat'
urlpatterns = [
    path('', views.video, name='video'),
    path('<str:room_name>/', views.chat, name='chat'),
    path('room/<str:room_name>/', views.video, name='video_room'),
]

appointments/models.py
from django.db import models
from accounts.models import User
from cloudinary.models import CloudinaryField


# Create your models here.
class Appointment(models.Model):
    APPROVAL_STATUS_CHOICES = [
        ('approved', 'Approved'),
        ('pending', 'Pending'),
        ('rejected', 'Rejected'),
        ('deleted', 'Deleted'),
        ('cancelled', 'Cancelled'),
    ]

    TIMESLOT_LIST = (
        (0, '09:00 - 09:30'),
        (1, '09:30 - 10:00'),
        (2, '10:00 - 10:30'),
        (3, '10:30 - 11:00'),
        (4, '11:00 - 11:30'),
        (5, '11:30 - 12:00'),
        (6, '12:00 - 12:30'),
        (7, '12:30 - 13:00'),
        (8, '13:00 - 13:30'),
        (9, '13:30 - 14:00'),
        (10, '14:00 - 14:30'),
        (11, '14:30 - 15:00'),
        (12, '15:00 - 15:30'),
        (13, '15:30 - 16:00'),
        (14, '16:00 - 16:30'),
        (15, '16:30 - 17:00'),
        (16, '17:00 - 17:30'),
    )

    doctor = models.ForeignKey(User, on_delete=models.DO_NOTHING, related_name='appointment_doctor', limit_choices_to={'user_type':'doctor'})
    patient = models.ForeignKey(User, on_delete=models.DO_NOTHING, related_name='appointment_patient', limit_choices_to={'user_type':'patient'})
    appointment_date = models.DateField(auto_now=False, auto_now_add=False)
    appointment_time = models.IntegerField(default=100, choices=TIMESLOT_LIST)
    reason = models.CharField(max_length=254)
    description = models.TextField(null=True)
    history_files = models.FileField(upload_to='patient_history_files/', null=True, blank=True)
    approval_status = models.CharField(max_length=10, choices = APPROVAL_STATUS_CHOICES, default='pending')

    def __str__(self):
        return self.reason

    @property
    def timeslot(self):
        return self.TIMESLOT_LIST[self.appointment_time][1]

appointments/forms.py
from django import forms
from .models import Appointment
from accounts.models import WorkingShift, User, DoctorProfile
from accounts.models import User, DoctorProfile, DoctorAvailability, WorkingShift
import datetime as dt
from cloudinary.forms import CloudinaryFileField

HOUR_CHOICES = [(dt.time(hour=x), '{:02d}:00'.format(x)) for x in range(0, 24)]

TIMESLOT_LIST = (
        (0, '09:00 - 09:30'),
        (1, '09:30 - 10:00'),
        (2, '10:00 - 10:30'),
        (3, '10:30 - 11:00'),
        (4, '11:00 - 11:30'),
        (5, '11:30 - 12:00'),
        (6, '12:00 - 12:30'),
        (7, '12:30 - 13:00'),
        (8, '13:00 - 13:30'),
        (9, '13:30 - 14:00'),
        (10, '14:00 - 14:30'),
        (11, '14:30 - 15:00'),
        (12, '15:00 - 15:30'),
        (13, '15:30 - 16:00'),
        (14, '16:00 - 16:30'),
        (15, '16:30 - 17:00'),
        (16, '17:00 - 17:30'),
    )

# doctor_profile = DoctorProfile.objects.get(doctor=User.objects.get(pk=request.session.pop('doctor_id')))
# HOUR_CHOICES = WorkingShift.objects.filter(doctor_profile=doctor_profile)

class CreateAppointmentForm(forms.Form):

    # def __init__(self, *args, **kwargs):
    #     working_shifts = kwargs.pop('working_shifts', None)
    #     working_days = []
    #     for shifts in working_shifts:
    #         working_days.append(shifts.working_day)
    #     super(CreateAppointmentForm, self).__init__(*args, **kwargs)
        # working_shifts = WorkingShift.objects.filter(doctor_profile = instance.doctorprofile)
        # self.fields['appointment_date'].widget = forms.Select(choices=working_days)
        # self.fields['appointment_time'].queryset = working_shifts


    # appointment_date = forms.ModelChoiceField(queryset=WorkingShift.objects.all())
    appointment_date = forms.DateField(widget=forms.DateInput(attrs={'type':'date'}))
    preferred_appointment_time = forms.ChoiceField(widget=forms.Select(attrs={'style': 'width: 200px;padding: 8px; margin-right: 16px;'}), choices = TIMESLOT_LIST)
    reason = forms.CharField(max_length=254)
    description = forms.CharField(widget=forms.Textarea(attrs={"rows":8, "cols":20}))
    files = CloudinaryFileField(label='Upload History Files',
        options = {
            'folder': 'hospsys/history_files/'
       },
       widget=forms.FileInput(attrs={'style':'width: 300px; padding: auto;', 'id':'history_files_upload', 'name':'history_files_upload'}),
    )
       

class DoctorAvailabilityForm(forms.Form):
    doctor = forms.ModelChoiceField(
    queryset=User.objects.filter(user_type='doctor').order_by(),
    widget=forms.Select(attrs={'style': 'width: 500px;padding: 8px; margin-right: 16px;'}))

class EditAppointmentForm(forms.ModelForm):
    appointment_date = forms.DateField(widget=forms.DateInput(attrs={'type':'date'}))
    appointment_time = forms.ChoiceField(widget=forms.Select(attrs={'style': 'width: 200px;padding: 8px; margin-right: 16px;'}), choices = TIMESLOT_LIST)
    reason = forms.CharField(max_length=254)
    description = forms.CharField(widget=forms.Textarea(attrs={"rows":8, "cols":20}))

    class Meta:
        model = Appointment
        fields = ['appointment_date','appointment_time', 'reason','description']

appointments/views.py
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.http import HttpResponse, HttpResponseRedirect
from .forms import CreateAppointmentForm, DoctorAvailabilityForm, EditAppointmentForm
from .models import Appointment
from accounts.models import User, DoctorProfile, WorkingShift, Department
from django.contrib import messages
from django.views import generic
from django.contrib.auth.decorators import login_required


# Create your views here.
def index(request):
    return HttpResponse("Appointment page")

@login_required
def choose_doctor(request):
    return render(request, 'appointments/choose_doctor.html')

@login_required
def create(request, doctor_id):
    if request.method == 'POST':
        if 'availability_submit' in request.POST:
            availability_form = DoctorAvailabilityForm(request.POST)
            create_form = CreateAppointmentForm()
            
            if availability_form.is_valid():
                doctor = availability_form.cleaned_data['doctor']
                doctor_query = User.objects.get(email=doctor.email)
                shifts = WorkingShift.objects.filter(doctor_profile=doctor_query.doctorprofile)

                context = {
                    'create_form': create_form,
                    'availability_form': availability_form,
                    'working_shifts': shifts,
                    'doctor': doctor,
                }
                return render(request, 'appointments/create_appointment.html', context)
        if 'create_appointment_submit' in request.POST:
            form = CreateAppointmentForm(request.POST, request.FILES)

            if form.is_valid():
                doctor = User.objects.get(pk=doctor_id)
                patient = request.user
                appointment_date = form.cleaned_data['appointment_date']
                appointment_time = form.cleaned_data['preferred_appointment_time']
                reason = form.cleaned_data['reason']
                description = form.cleaned_data['description']
                breakpoint()

                history_files = request.FILES['files'].name

                try:
                    existing_appointment = Appointment.objects.get(doctor=doctor, patient=patient)
                except Appointment.DoesNotExist:
                    existing_appointment = None

                if existing_appointment is not None:
                    # messages.add_message(request, messages.ERROR, 'Appointment with doctor already exists.')
                    messages.error(request,'You already have an appointment with this doctor. Please check your dashboard for your appointments.')

                    return HttpResponseRedirect(reverse('appointments:create_appointment', args=(doctor_id,)))
                else:
                    doctor_appointments = Appointment.objects.filter(doctor=doctor)
                    for appoint in doctor_appointments:
                        if int(appoint.appointment_time) == int(appointment_time):
                            messages.error(request, 'The time slot is already booked. Please try another time slot for appointment')
                            return HttpResponseRedirect(reverse('appointments:create_appointment', args=(doctor_id,)))
                            
                    obj, created = Appointment.objects.update_or_create(patient = patient, doctor=doctor,defaults={'doctor':doctor, 'appointment_date':appointment_date, 'appointment_time': appointment_time, 'reason':reason, 'description':description, 'history_files': history_files })
                    if created:
                        return HttpResponseRedirect(reverse('accounts:dashboard'))
            else:
                messages.add_message(request, messages.ERROR, 'Invalid data')
                return render(request, 'accounts/patient_dashboard.html')
    else:
        doctor = User.objects.get(pk=doctor_id)
        request.session['doctor_id'] = doctor_id
        working_shifts = WorkingShift.objects.filter(doctor_profile=doctor.doctorprofile)
        create_form = CreateAppointmentForm()
        availability_form = DoctorAvailabilityForm()

        context = {
            'create_form': create_form,
            'availability_form': availability_form,
            'doctor': doctor,
            'working_shifts': working_shifts,
        }
    return render(request, 'appointments/create_appointment.html', context)

@login_required
def edit(request, appointment_id):
    if request.method == 'POST':
        appointment = Appointment.objects.get(pk=appointment_id)
        doctor = appointment.doctor
        form = EditAppointmentForm(request.POST, instance=appointment)
        if form.is_valid():
            doctor_appointments = Appointment.objects.filter(doctor=doctor)
            for appoint in doctor_appointments:
                if (appoint.patient != request.user and int(appoint.appointment_time) == int(appointment.appointment_time)):
                    messages.error(request, 'The time slot is already booked. Please try another time slot for appointment')
                    return HttpResponseRedirect(reverse('appointments:edit_appointment', args=(appointment.id,)))
            # appointment_date = form.cleaned_data['appointment_date']
            # appointment_time = form.cleaned_data['appointment_time']
            # reason = form.cleaned_data['reason']
            # description = form.cleaned_data['description']
            form.save()
            messages.success(request, "Appointment updated successfully.")
            return HttpResponseRedirect(reverse('appointments:view_details', args=(appointment.id,)))

    appointment = Appointment.objects.get(pk=appointment_id)
    form = EditAppointmentForm(instance=appointment)
    context = {
        'appointment': appointment,
        'edit_form': form,
    }
    return render(request, 'appointments/edit_appointment.html', context)

@login_required
def doctor_availability(request):
    if request.method == 'POST':
        form = DoctorAvailabilityForm(request.POST)
        if form.is_valid():
            doctor = form.cleaned_data['doctor']
            doctor_query = User.objects.get(email=doctor.email)
            shifts = WorkingShift.objects.filter(doctor_profile=doctor_query.doctorprofile)
            return render(request, 'appointments/check_doctor_availability.html', {'form': form, 'working_shifts': shifts, 'doctor': doctor})
    else:
        form = DoctorAvailabilityForm()
    return render(request, 'appointments/check_doctor_availability.html', {'form': form})

@login_required
def set_approval_status(request, pk):
    if request.method == 'POST':
        status = request.POST['approval_status']
        if status == 'Approve':
            approval_status = 'approved'
        if status == 'Reject':
            approval_status = 'rejected'
        if status == 'Pending':
            approval_status = 'pending'
        if status == 'Cancel':
            approval_status = 'cancelled'
        if status == 'Delete':
            approval_status = 'deleted'
    try:
        appointment = Appointment.objects.get(pk=pk)
        appointment.approval_status = approval_status
        appointment.save()
        return HttpResponseRedirect(reverse('accounts:dashboard'))
    except Appointment.DoesNotExist:
        return HttpResponseRedirect(reverse('accounts:dashboard'))

@login_required
def delete(request, appointment_id):
    appointment = get_object_or_404(Appointment, pk=appointment_id)
    appointment.delete()
    messages.success(request, "Appointment Deleted.")
    return HttpResponseRedirect(reverse('accounts:dashboard'))
 
@login_required
def cancel_appointment(request, appointment_id):
    appointment = get_object_or_404(Appointment, pk=appointment_id)
    appointment.approval_status = 'cancelled'
    appointment.save()
    return HttpResponseRedirect(reverse('accounts:dashboard'))

@login_required
def doctors(request):
    doctors = User.objects.filter(user_type='doctor')
    departments = Department.objects.all()
    context = {
        'doctors': doctors,
        'departments': departments,
    }
    return render(request, 'appointments/doctors.html', context)


class AppointmentDetailView(generic.DetailView):
    model = Appointment
    template_name = 'appointments/appointment_details.html'

appointments/templates/appointments/appointment_details.html
{% extends 'accounts/layouts/starter.html' %}


{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header p-4">
                    <h5 class="m-0">Appointment Details</h5>
                </div>

                <div class="card-body">
                    <div>
                    {% if messages %}
                        {% for message in messages %}

                        <div class="alert alert-success alert-dismissible fade show col-12" role="alert">
                            {{ message }}
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                              <span aria-hidden="true">&times;</span>
                            </button>
                          </div>
                          {% endfor %}

                    {% endif %}
                    </div>
                    
                    <div class="row">

                        <div class="col-6">
                            <table id="" class="table table-bordered appointment-details-info patient-info">
                                <thead>
                                    <tr>
                                        <td colspan="2">Patient Information</td>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <td>Name:</td>
                                        <td>{{ appointment.patient.get_full_name.title }}</td>
                                    </tr>
                                    <tr>
                                        <td>Address:</td>
                                        <td>{{ appointment.patient.patientprofile.get_full_address }}</td>
                                    </tr>
                                    <tr>
                                        <td>Contact No:</td>
                                        <td>{{ appointment.patient.get_full_name.title }}</td>
                                    </tr>
                                    <tr>
                                        <td>Email:</td>
                                        <td>{{ appointment.patient.email }}</td>
                                    </tr>
                                </tbody>
                                
                            </table>
                        </div>
                        <div class="col-6">
                            <table id="" class="table table-bordered appointment-details-info doctor-info">
                                <thead>
                                    <tr>
                                        <td colspan="2">Doctor Information</td>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <td>Name:</td>
                                        <td>{{ appointment.doctor.get_full_name.title }}</td>
                                    </tr>
                                    <tr>
                                        <td>Department</td>
                                        <td>{{ appointment.doctor.doctorprofile.department }}</td>
                                    </tr>
                                    <tr>
                                        <td>Contact No:</td>
                                        <td>{{ appointment.doctor.get_full_name.title }}</td>
                                    </tr>
                                    <tr>
                                        <td>Email:</td>
                                        <td>{{ appointment.doctor.email }}</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <br>
                    <div class="row">
                        <div class="col-12">
                            <table id="" class="table table-bordered appointment-details-table">
                                <thead>
                                    <tr>
                                        <td colspan="2">Appointment Details</td>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <td>Appointment Date:</td>
                                        <td>{{ appointment.appointment_date}}</td>
                                    </tr>
                                    <tr>
                                        <td>Appointment Time:</td>
                                        <td>{{ appointment.timeslot }}</td>
                                    </tr>
                                    <tr>
                                        <td>Reason:</td>
                                        <td>{{ appointment.reason }}</td>
                                    </tr>
                                    <tr>
                                        <td>Description:</td>
                                        <td>{{ appointment.description }}</td>
                                    </tr>
                                    <tr>
                                        <td>User Uploaded Files:</td>
                                        <td><a href="{{appointment.history_files.url}}">{{ appointment.history_files }}</a></td>
                                    </tr>
                                    
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div class="row">

                        <div class="col-12 text-center mb-3">
                            {% if appointment.approval_status == 'approved' %}
                            <p class="p-3 bg-success">Your appointment request has been approved.</p>

                            <a class="btn btn-lg btn-success" href="{% url 'video_chat:video' %}">Join Call</a>
                            {% else %}
                            <p class="p-3 bg-warning">Your appointment request is pending...</p>
                           
                            {% endif %}
                        </div>
                        
                        <div class="col-12">
                            <a class="float-left btn btn-secondary" href="{% url 'accounts:dashboard' %}">Back</a>
                            <a class="float-left btn btn-info ml-2" href="{% url 'appointments:edit_appointment' appointment.id %}">Edit</a>
                            <a class="float-right" href="{% url 'appointments:cancel_appointment' appointment.id %}">Cancel this appointment</a>
                        </div>
                        
                    </div>
                        
                </div> <!-- card body-->
            </div> <!-- card -->
        </div> <!-- col-md-12 -->
    </div> <!-- row -->
    

    
</div> <!-- container -->

{% endblock content %}

appointments/templates/appointments/check_doctor_availability.html
{% extends 'accounts/layouts/starter.html' %}
{% load crispy_forms_tags %}
{% block title %} Doctor Availability {% endblock title %}

{% block content %}
<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-header p-3">
                <h4 class="card-title">Doctor Availability</h4>
            </div>
            <div class="card-body">
                <form method="post" class="form m-3">
                    {% csrf_token %}
                    {{ form }}
                    <input type="submit" class="btn btn-primary" value="View Availability">
                </form>
                <br>

                <div class="doctor-availability-table row">
                    <table name="view-availability-table" class="table table-bordered col-6 m-3">
                        <thead>
                            <tr class="bg-info">
                                <th class="">Working Days</th>
                                <th class="">Shift Start Time</th>
                                <th class="">Shift End Time</th>
                                <!-- <th class=""></th> -->
                            </tr>
                        </thead>
                        <tbody>
                            {% for shift in working_shifts %}
                                <tr>
                                    <td>{{ shift.working_day }}</td>
                                    <td>{{ shift.start_time }}</td>
                                    <td>{{ shift.end_time }}</td>
                                </tr>
                            {% endfor %}
                        </tbody>
        
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

appointments/templates/appointments/create_appointment.html
{% extends 'accounts/layouts/starter.html' %}
{% load crispy_forms_tags %}
{% block title %} Create Appointment{% endblock title %}

{% block content %}
<div class="row">
    <div class="col-lg-8">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title">Create Appointment</h4>
            </div>
            <div class="card-body">
                {% if messages %}
                <ul class="messages pl-0">
                    {% for message in messages %}
            
                    <p class="alert alert-warning m-0">{{ message }}</p>

                    {% endfor %}
                </ul>
                {% endif %}
                <p class="bg-info p-3">Please check your doctors before making appointments.</p>
                <form method="post" enctype="multipart/form-data">
                    <label for="doctor_name">Appointment with Doctor: </label>
                    <input type="text" name="doctor" id="doctor" class="form-control" value="{{ doctor.get_full_name }}" readonly><br>
                    {% csrf_token %}
                    {{ create_form|crispy }}
                    <input type="submit" class="btn btn-primary" name="create_appointment_submit" value="Create Appointment">
                </form>
            </div>
        </div>
    </div>
    <div class="col-lg-4">
        <div class="card">
            <div class="card-header bg-info p-3">
                <h4 class="card-title">Doctor Availability</h4>
            </div>
            <div class="card-body">
                <label for="doctor_name">Doctor</label>
                <input type="text" class="form-control" value="{{ doctor.get_full_name }}" readonly><br>

                <div class="doctor-availability">
                    <table name="view-availability-table" class="table table-bordered">
                        <thead>
                            <tr>
                                <th class="col-6">Working Days</th>
                                <th class="col-3">Shift Start Time</th>
                                <th class="col-3">Shift End Time</th>
        
                            </tr>
                        </thead>
                        <tbody>
                            {% for shift in working_shifts %}
                                <tr>
                                    <td>{{ shift.working_day }}</td>
                                    <td>{{ shift.start_time }}</td>
                                    <td>{{ shift.end_time }}</td>
                                  
                                </tr>
                            {% endfor %}
                        </tbody>
        
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>  
<div class="row">
   
</div>

<script>
    var doctorname = document.getElementById('id_doctor');
    console.log(doctorname);
    var doctor = document.querySelector('#doctor-available-hours');
    doctorname.addEventListener('change', function(){
        var loc = window.location;
        var endPoint = 'ws://' + loc.host + loc.pathname;
        var webSocket = new WebSocket(endPoint);

        webSocket.addEventListener('open', ()=> {
            console.log("Websocket connection for doctor open.");
        });
        webSocket.addEventListener('close', ()=> {
            console.log("Websocket connection for doctor closed.");
        });

    });
</script>
{% endblock content %}

appointments/templates/appointments/view_appointments.html
view appointments