accounts/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views
from django.urls import reverse

app_name = 'accounts'
urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('register/', views.register, name='register'),
    path('register_profile/<str:user_type>/', views.register_profile, name='register_profile'),
    path('password_change/', auth_views.PasswordChangeView.as_view(success_url='/accounts/login/'), name='password_change'),
    path('password_reset/', views.password_reset_request, name='password_reset'),
    # path('password_reset/', auth_views.PasswordResetView.as_view(template_name='accounts/password/password_reset.html'), name='password_reset'),
    # path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='accounts/password/password_reset_done.html'), name='password_reset_done'),
    # path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password/password_reset_confirm.html'), name='password_reset_confirm'),
    # path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password/password_reset_complete.html'), name='password_reset_complete'), 
    path('profile/<int:user_id>', views.profile, name='profile'),
    path('', views.dashboard, name='dashboard'),
    path('working_shifts/edit/', views.edit_working_shifts, name='edit_working_shifts'),
    path('working_shifts/', views.view_working_shifts, name='view_working_shifts'),
    path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', views.activate, name='activate'),
    # path('', views.index),
]

appointments/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from .views import AppointmentDetailView

app_name = 'appointments'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/<int:doctor_id>', views.create, name='create_appointment'),
    path('edit/<int:appointment_id>', views.edit, name='edit_appointment'),
    path('doctors/', views.doctors, name='list_doctors'),
    path('doctor-availability/', views.doctor_availability, name='doctor_availability'),
    path('approve-status/<int:pk>', views.set_approval_status, name='set_approval_status'),
    path('details/<int:pk>', AppointmentDetailView.as_view(), name='view_details'),
    path('delete/<int:appointment_id>', views.delete, name='delete_appointment'),
    path('cancel/<int:appointment_id>', views.cancel_appointment, name='cancel_appointment'),
]

hospsys/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('appointments/', include('appointments.urls')),
    path('video_chat/', include('video_chat.urls')),
    path("__reload__/", include("django_browser_reload.urls")),
     path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='accounts/password/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password/password_reset_confirm.html'), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password/password_reset_complete.html'), name='password_reset_complete'), 

]

video_chat/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'video_chat'
urlpatterns = [
    path('', views.video, name='video'),
    path('<str:room_name>/', views.chat, name='chat'),
    path('room/<str:room_name>/', views.video, name='video_room'),
]

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import User, DoctorAvailability, WorkingShift, DoctorProfile, PatientProfile,Department
from django import forms
from django.forms import ModelForm, fields
import datetime as dt
from entangled.forms import EntangledModelForm
from cloudinary.forms import CloudinaryFileField


class RegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['email', 'username','first_name', 'middle_name', 'last_name','user_type']

DAY_CHOICES = (
        ('sunday', 'Sunday'),
        ('monday', 'Monday'),
        ('tuesday', 'Tuesday'),
        ('wednesday', 'Wednesday'),
        ('thursday', 'Thursday'),
        ('friday', 'Friday'),
        ('saturday', 'Saturday'),
    )
HOUR_CHOICES = [(dt.time(hour=x), '{:02d}:00'.format(x)) for x in range(0, 24)]

# class DoctorAvailabilityForm(forms.Form):
#     available_days = forms.MultipleChoiceField(widget=forms.CheckboxSelectMultiple(), choices = DAY_CHOICES)
#     available_start_time = forms.ChoiceField(widget=forms.Select(), choices = HOUR_CHOICES)
#     available_end_time = forms.ChoiceField(widget=forms.Select(), choices = HOUR_CHOICES)

# class DoctorAvailabilityForm(EntangledModelForm):
#     days= fields.MultipleChoiceField(widget=forms.CheckboxSelectMultiple(), choices=DAY_CHOICES)
#     start_time = fields.ChoiceField(choices = HOUR_CHOICES)
#     end_time = fields.ChoiceField(choices = HOUR_CHOICES)

#     class Meta:
#         model = DoctorAvailability
#         entangled_fields = {'working_shifts': ['days', 'start_time', 'end_time']}
#         untangled_fields = ['doctor','available_status']
#         exclude = ['doctor','available_status']

class RegistrationProfileForm(forms.ModelForm):
    class Meta:
        model = DoctorProfile
        fields = ['department', 'nmc']

class DoctorWorkingShiftForm(forms.Form):
    working_day = forms.ChoiceField(widget=forms.Select(attrs={'style': 'width: 200px;padding: 8px; margin-right: 16px;'}), choices = DAY_CHOICES)
    start_time = forms.ChoiceField(widget=forms.Select(attrs={'style': 'width: 200px;padding: 8px; margin-right: 16px;'}), choices = HOUR_CHOICES)
    end_time = forms.ChoiceField(widget=forms.Select(attrs={'style': 'width: 200px;padding: 8px; margin-right: 16px;'}), choices = HOUR_CHOICES)
    
    # class Meta:
    #     model = WorkingShift
    #     exclude = ['doctor_profile']
    #     widget = {
    #         'start_time': forms.MultipleChoiceField(widget=forms.CheckboxSelectMultiple(), choices = DAY_CHOICES)
    #     }

class UpdateUserForm(forms.ModelForm):
    profile_image = CloudinaryFileField(label=False,
        options = {
            'crop': 'thumb',
            'width': 500,
            'height': 500,
            'folder': 'hospsys_profile'
       },
       widget=forms.FileInput(attrs={'style':'width: 300px; padding: auto; display:none;', 'id':'profile_image_upload'}),
    )
    class Meta:
        model = User
        fields = ['profile_image','email', 'username', 'first_name','middle_name','last_name']

class PatientProfileForm(forms.ModelForm):
    class Meta:
        model = PatientProfile
        fields = ['address_street', 'address_city']

class DoctorProfileForm(forms.ModelForm):
    class Meta:
        model = DoctorProfile
        fields = ['department', 'nmc']

accounts/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from .forms import RegistrationForm, DoctorWorkingShiftForm, RegistrationProfileForm, UpdateUserForm, PatientProfileForm, DoctorProfileForm
from django.urls import reverse
from .models import DoctorAvailability, DoctorProfile, WorkingShift, User
from django.views.generic.edit import UpdateView
from appointments.models import Appointment
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.core.mail import EmailMessage, send_mail, BadHeaderError
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.contrib.auth.tokens import default_token_generator
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import PasswordResetForm
from django.db.models.query_utils import Q

# Create your views here.
def index(request):
    return HttpResponse("index page.")

def register(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()
            token = default_token_generator.make_token(user)
            current_site = get_current_site(request)
            mail_subject = 'Activate your account.'
            message = render_to_string('registration/activation_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid':urlsafe_base64_encode(force_bytes(user.pk)),
                'token': token,
            })
            to_email = form.cleaned_data.get('email')
            email = EmailMessage(
                        mail_subject, message, to=[to_email]
            )
            email.send()
            messages.success(request,'Please verify your account before logging in.')
            return HttpResponseRedirect(reverse('accounts:login'))
    else:
        form = RegistrationForm()
    return render(request, 'registration/register.html', {'form': form})

def register_profile(request, user):
    if request.method == 'POST':
        pass
    else:
        form = RegistrationProfileForm()
    return render(request, 'registration/register_profile.html', {'form': form})

def activate(request, uidb64, token):
    try:
        uid = urlsafe_base64_decode(uidb64)
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and default_token_generator.check_token(user, token):
        user.is_active = True
        user.save()
        # login(request, user)
        # return redirect('home')
        messages.success(request,'Account verified. You can login now.')
        return HttpResponseRedirect(reverse('accounts:login'))
    else:
        return HttpResponse('Activation link is invalid!')

def password_reset_request(request):
	if request.method == "POST":
		password_reset_form = PasswordResetForm(request.POST)
		if password_reset_form.is_valid():
			data = password_reset_form.cleaned_data['email']
			associated_users = User.objects.filter(Q(email=data))
			if associated_users.exists():
				for user in associated_users:
					subject = "Password Reset Requested"
					email_template_name = "accounts/password/password_reset_email.txt"
					c = {
					"email":user.email,
					'domain': get_current_site(request).domain,
					'site_name': 'HospSys',
					"uid": urlsafe_base64_encode(force_bytes(user.pk)),
					"user": user,
					'token': default_token_generator.make_token(user),
					'protocol': 'http',
					}
					email = render_to_string(email_template_name, c)
					try:
						send_mail(subject, email, 'admin@admin.com' , [user.email], fail_silently=False)
					except BadHeaderError:
						return HttpResponse('Invalid header found.')
					return redirect ("/password_reset/done/")
	password_reset_form = PasswordResetForm()
	return render(request=request, template_name="accounts/password/password_reset.html", context={"password_reset_form":password_reset_form})

@login_required
def dashboard(request):
    if request.user.is_authenticated:
        user = request.user
        if user.is_doctor:
            working_shifts_form = DoctorWorkingShiftForm()
            appointments = Appointment.objects.filter(doctor = user)
            context = {
                'current_user': user,
                'working_shifts_form': working_shifts_form,
                'appointments': appointments,
            }
            return render(request, 'accounts/doctor_dashboard.html', context)
        elif user.is_patient:
            appointments = Appointment.objects.filter(patient = user, approval_status__in = ['pending', 'approved'])
            context = {
                'current_user': user,
                'appointments': appointments,
            }
            return render(request, 'accounts/patient_dashboard.html', context)
        else:
            return HttpResponseRedirect(reverse('accounts:login'))
    else:
        return HttpResponseRedirect(reverse('accounts:login'))

@login_required
def profile(request, user_id):
    if request.method == 'POST':
        userform = UpdateUserForm(request.POST, request.FILES, instance=request.user)
        if request.user.user_type == 'patient':
            profileform = PatientProfileForm(request.POST, instance=request.user.patientprofile)
        else:
            profileform = DoctorProfileForm(request.POST, instance=request.user.doctorprofile)
        if userform.is_valid() and profileform.is_valid():
            userform.save()
            profileform.save()
            messages.success(request,"Profile successfully updated.")
            return redirect('accounts:profile', user_id=request.user.id)
    else:
        userform = UpdateUserForm(instance=request.user)
        if request.user.user_type == 'patient':
            profileform = PatientProfileForm(instance=request.user.patientprofile)
        else:
            profileform = DoctorProfileForm(instance=request.user.doctorprofile)


        context = {
            'userform': userform,
            'profileform': profileform,
        }
        return render(request, 'accounts/profile.html', context)
        
@login_required
def view_working_shifts(request):
    if request.user.is_authenticated:
        if request.user.user_type == 'doctor':
            working_shifts = WorkingShift.objects.filter(doctor_profile = request.user.doctorprofile)
            return render(request, 'accounts/view_availability.html', {'working_shifts': working_shifts})
        else:
            return HttpResponseRedirect(reverse('accounts:dashboard'))
    

# def change_availability(request):
#     if request.method == 'POST':
#         form = DoctorAvailabilityForm(request.POST)
#         available_days = []

#         if form.is_valid():
#             av_days = form.cleaned_data['available_days']
#             for av_day in av_days:
#                 available_days.append(av_day) 
#             available_start_time = form.cleaned_data['available_start_time']
#             available_end_time = form.cleaned_data['available_end_time']
#             doctor = request.user.doctorprofile
#             available_status = 'offline'
#             dav = DoctorAvailability.objects.filter(doctor=request.user.doctorprofile).update(available_days=available_days, available_start_time=available_start_time, available_end_time=available_end_time, available_status=available_status, doctor=doctor)
#             # dav_update = dav.update(available_days=available_days, available_start_time=available_start_time, available_end_time=available_end_time, available_status=available_status, doctor=doctor)
#             return HttpResponseRedirect(reverse('accounts:dashboard'))
#             # if da.update_or_create():
#             #     return HttpResponseRedirect(reverse('accounts:dashboard'))
#             # else:
#             #     return render(request, 'accounts/change_availability.html', {'form': form})            
#     else:
#         # doctorprofile = DoctorProfile.objects.get(doctor=request.user)
#         # dav = doctorprofile.doctoravailability
#         # av_days = dav.available_days
#         # av_start_time = dav.available_start_time
#         # av_end_time = dav.available_end_time
#         # av_status = dav.available_status
#         # data = {
#         #     'available_days': av_days,
#         #     'available_start_time': av_start_time,
#         #     'available_end_time': av_end_time,
#         #     'available_status': av_status,
#         #     'doctor': request.user
#         # }
#         # working_shifts = DoctorAvailability.objects.filter(doctor=request.user.doctorprofile).values('working_shifts')        
#         form = DoctorAvailabilityForm()
#     return render(request, 'accounts/change_availability.html', {'form': form})

@login_required
def edit_working_shifts(request):
    if request.user.is_authenticated:
        if request.user.user_type == 'doctor':
            if request.method == 'POST':
                form = DoctorWorkingShiftForm(request.POST)

                if form.is_valid():
                    doctor_profile = request.user.doctorprofile
                    working_day = form.cleaned_data['working_day']
                    start_time = form.cleaned_data['start_time']
                    end_time = form.cleaned_data['end_time']
                    obj, created = WorkingShift.objects.update_or_create(doctor_profile=doctor_profile, working_day=working_day, defaults = {'start_time':start_time, 'end_time': end_time})
                    # obj = form.save(commit=False)
                    # obj.doctor_profile = doctor_profile
                    # obj.save()
                    if obj:

accounts/templates/accounts/change_availability.html
{% extends 'accounts/layouts/starter.html' %}
{% load crispy_forms_tags %}

{% block title %} Working Hours {% endblock %}

{% block content %}
<div class="container-fluid">
    <div class="card">
        <div class="card-header">
            <h3>Edit Working Shifts</h3>
        </div>
        
        <div class="card-body">
            <div class="card">
                <div class="card-header bg-secondary">
                    <h5 class="card-title">Current Working Shifts</h5>
                </div>
                <div class="card-body">
                    <table name="view-availability-table" class="table table-bordered">
                        <thead>
                            <tr>
                                <th class="col-6">Working Days</th>
                                <th class="col-3">Shift Start Time</th>
                                <th class="col-3">Shift End Time</th>
            
                            </tr>
                        </thead>
                        <tbody>
                            {% for shift in working_shifts %}
                                <tr>
                                    <td>{{ shift.working_day.title }}</td>
                                    <td>{{ shift.start_time }}</td>
                                    <td>{{ shift.end_time }}</td>
                                </tr>
                            {% endfor %}
                        </tbody>
            
                    </table>
                </div>
            </div>
            <br>
            <hr>
            <br>

            <div class="card">
                <div class="card-header bg-primary">
                    <h5 class="card-title">Add or Edit Working Shifts</h5>
                </div>
                <div class="card-body">
                    <form method="post" class="form">
                        {% csrf_token %}
                        {{ form }}       
        
                        <input type="submit" value="Save" class="btn btn-primary">
                    </form>
                </div>
                
            </div>
           
        </div>
    
    </div>
    
</div>
{% endblock content %}

accounts/templates/accounts/doctor_dashboard.html
{% extends 'accounts/layouts/starter.html' %}
{% load crispy_forms_tags %}

{% block title %} Dashboard {% endblock %}

{% block content %}
   
<div class="row mb-2">
    <div class="col-sm-6">
    <h1 class="m-0">
        Doctor Dashboard
    </h1>
    </div><!-- /.col -->
    <div class="col-sm-6">
    <ol class="breadcrumb float-sm-right">
        <li class="breadcrumb-item"><a href="#">Home</a></li>
        <li class="breadcrumb-item active">Dashboard</li>
    </ol>
    </div><!-- /.col -->
</div><!-- /.row -->

<div class="row m-2">
  {% if current_user.doctorprofile.profile_incomplete %}
  <div class="alert alert-warning alert-dismissible fade show col-12" role="alert">
    Please complete your profile.
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  {% endif %}

  {% if not current_user.doctorprofile.is_nmc_verified %}
  <div class="alert alert-warning alert-dismissible fade show col-12" role="alert">
    Your NMC registration has not been verified yet. Please contact administrator.<br>
    Your dashboard will be available once your NMC registration is verified.
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  {% endif %}
</div>
</div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->

{% if current_user.doctorprofile.is_nmc_verified %}


<!-- Main content -->
<div class="content">
  <div class="container-fluid">
    <!-- /.row -->
    <div class="row">
      <div class="col-12">
        <div class="card">
          <div class="card-header bg-info p-3">
            <h3 class="card-title">Scheduled Appointments</h3>
          </div>
          <!-- ./card-header -->
          <div class="card-body">
            <table class="table table-bordered table-hover appointment-table">
              <thead>
                <tr class="row">
                  <th class="col-1">#</th>
                  <th class="col-4">Patient Name</th>
                  <th class="col-2">Date</th>
                  <th class="col-2">Time</th>
                  <th class="col-2">Reason</th>
                  <th class="col-1">Status</th>
                </tr>
              </thead>
              <tbody>
                  {% for appointment in appointments %}
                      <tr data-widget="expandable-table" aria-expanded="false" class="row">
                        <td class="col-1">
                          <a href="#" style="margin-left: 20px;"><i class="fas fa-edit"></i></a>                            
                        </td>
                        <td class="col-4">{{ appointment.patient.get_full_name.title }}</td>
                        <td class="col-2">{{ appointment.appointment_date }}</td>
                        <td class="col-2">{{ appointment.appointment_time }}</td>
                        <td class="col-2">{{ appointment.reason.capitalize }}</td>
                        <td class="col-1">{{ appointment.approval_status.title }}</td>
                      </tr>
                      <tr class="expandable-body row">
                        <td class="col-11">
                          <div class="">
                            <p class="p-3">{{ appointment.description }}</p>

                          </div>

                          <div class="text-center">
                            {% if appointment.approval_status != 'approved' %}
                            <p><a href="#" class="btn btn-secondary">Join Call</a></p>
                          {% else %}
                            <p><a href="{% url 'video_chat:video' %}" class="btn btn-success">Join Call</a></p>
                          {% endif %}
                          </div>
                          
                        </td>
                        <td class="col-1">
                          <form method="post" action="{% url 'appointments:set_approval_status' appointment.id %}" style="margin: 10px;">
                            {% csrf_token %}
                            <input type="submit" name="approval_status" class="btn btn-success" style="margin: 10px;" value="Approve">
                            <input type="submit" name="approval_status" class="btn btn-danger" style="margin: 10px;" value="Reject">
                            <input type="submit" name="approval_status" class="btn btn-secondary" style="margin: 10px;" value="Pending">

                          </form>
                        </td>
                      </tr>
                  {% endfor %}
                

              </tbody>
            </table>
          </div>
          <!-- /.card-body -->
        </div>
        <!-- /.card -->
      </div>
    </div>
        <!-- /.row -->
  
      

{% endif %}

{% endblock content %}

accounts/templates/accounts/patient_dashboard.html
{% extends 'accounts/layouts/starter.html' %}
{% load static %}
{% block title %} Dashboard {% endblock %}

{% block content %}
  
  <div class="row mb-2">
    <div class="col-sm-6">
      <h1 class="m-0">
        Patient Dashboard
      </h1>
    </div><!-- /.col -->
    <div class="col-sm-6">
      <ol class="breadcrumb float-sm-right">
        <li class="breadcrumb-item"><a href="#">Home</a></li>
        <li class="breadcrumb-item active">Starter Page</li>
      </ol>
    </div><!-- /.col -->
  </div><!-- /.row -->

  <div class="row">
    {% if current_user.patientprofile.profile_incomplete %}
    <div class="alert alert-warning alert-dismissible fade show col-8" role="alert">
      Please complete your profile.
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% endif %}
  </div>
</div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->



<!-- Main content -->
<div class="content">
<div class="container-fluid">
  <div class="row">
  
    <div class="col-md-12">
      <div class="card">
        <div class="card-header">
          <h5 class="p-2">Your Appointments</h5>
        </div>
        <div class="row appointment-messages">
            {% if messages %}
            {% for message in messages %}
            <div class="alert alert-warning alert-dismissible fade show" role="alert">
              {{message}}
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            {% endfor %}

            {% endif %}
        </div>
        <div class="row">
        {% for appointment in appointments %}
        <div class="col-2">
          <div class="card m-4 appointment-card" style="width: 16rem;">
            <div class="card-header {% if appointment.approval_status == 'approved'%}bg-success{% else %} bg-secondary {% endif %}">{{ appointment.approval_status.title }}</div>
            <img class="card-img-top" src="{% static 'accounts/images/logos/logo-transparent.png' %}" alt="Card image cap">
            <div class="card-body">
              <h5 class="card-title"><b>Dr. {{ appointment.doctor.get_full_name }}  &nbsp;|&nbsp;  </b> <br><small>{{ appointment.doctor.doctorprofile.department }}</small></h5>
              <p class="card-text">
                <ul style="list-style-type: none; padding-left: 0">
                  <li><b>Date:</b> {{ appointment.appointment_date }}</li>
                  <li><b>Time:</b> {{ appointment.timeslot }}</li>
                </ul>
              </p>
              <a href="{% url 'appointments:view_details' appointment.id %}" id="btn-appointment-details" class="btn btn-primary" style="width: 100%;">View Details</a>
            </div>
          </div>
        </div>
       
        
        {% endfor %}
        </div>
        
      </div>
    </div>
    <!-- /.col-md-6 -->
  </div>
  <!-- /.row -->

{% endblock content %}

accounts/templates/accounts/profile.html
{% extends 'accounts/layouts/starter.html' %}
{% load crispy_forms_tags %}
{% load cloudinary %}


{% block title %} Profile {% endblock %}

{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <h3>Profile</h3>
                </div>
                
                <div class="card-body">

                    {% if messages %}
                        {% for message in messages %}
                            <div class="alert alert-{{message.tags}} alert-dismissible fade show col-12" role="alert">
                            {{message}}
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                            </div>
                        {% endfor %}

                    {% endif %}

                    <div class="row">
                        <div class="col-12">
                            <div class="card">
                                <div class="card-header bg-secondary">
                                    <h5 class="card-title">My Details</h5>
                                </div>
                                <div class="card-body">
                                    <form method="post" enctype="multipart/form-data">
                                        <div class="profile_upper_div">
                                            <img src="{{ request.user.profile_image.url }}" class="img-circle" height="200px" width="200px" style="margin: 20px;"><br>

                                            <div class="profile_image_actions">
                                                <input type="button" class="btn btn-small btn-success mr-3" value="Change Profile Picture" onclick="document.getElementById('profile_image_upload').click()">
                                                <a class="btn btn-small btn-success" href="{{request.user.profile_image.url}}" target="_blank">View Profile Picture</a>
                                            </div>
                                        </div>
                                        
                                        {% csrf_token %}
                                        {{ userform|crispy }}
                                        {{ profileform|crispy }}

                                        <input type="submit" class="btn btn-success" value="Save">
                                    </form>
                                  
                                    
                                </div>
                            </div>  
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-12">
                            <div class="card">
                                <div class="card-header bg-secondary">
                                    <h5 class="card-title">Change Password</h5>
                                </div>
                                <div class="card-body">
                                    <a href="{% url 'accounts:password_change' %}">Change Account Password</a>
                                </div>
    
                            </div>
                        </div>
                        
                    </div>
                             
                   
                </div> <!-- card body -->
            
            </div> <!-- card -->
        </div> <!-- col-6 -->
        
    </div><!-- row -->
   
    
</div> <!-- container -->
{% endblock content %}