accounts/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views
from django.urls import reverse

app_name = 'accounts'
urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('register/', views.register, name='register'),
    path('register_profile/<str:user_type>/', views.register_profile, name='register_profile'),
    path('password_change/', auth_views.PasswordChangeView.as_view(success_url='/accounts/login/'), name='password_change'),
    path('password_reset/', views.password_reset_request, name='password_reset'),
    # path('password_reset/', auth_views.PasswordResetView.as_view(template_name='accounts/password/password_reset.html'), name='password_reset'),
    # path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='accounts/password/password_reset_done.html'), name='password_reset_done'),
    # path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password/password_reset_confirm.html'), name='password_reset_confirm'),
    # path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password/password_reset_complete.html'), name='password_reset_complete'), 
    path('profile/<int:user_id>', views.profile, name='profile'),
    path('', views.dashboard, name='dashboard'),
    path('working_shifts/edit/', views.edit_working_shifts, name='edit_working_shifts'),
    path('working_shifts/', views.view_working_shifts, name='view_working_shifts'),
    path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', views.activate, name='activate'),
    # path('', views.index),
]

appointments/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from .views import AppointmentDetailView

app_name = 'appointments'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/<int:doctor_id>', views.create, name='create_appointment'),
    path('edit/<int:appointment_id>', views.edit, name='edit_appointment'),
    path('doctors/', views.doctors, name='list_doctors'),
    path('doctor-availability/', views.doctor_availability, name='doctor_availability'),
    path('approve-status/<int:pk>', views.set_approval_status, name='set_approval_status'),
    path('details/<int:pk>', AppointmentDetailView.as_view(), name='view_details'),
    path('delete/<int:appointment_id>', views.delete, name='delete_appointment'),
    path('cancel/<int:appointment_id>', views.cancel_appointment, name='cancel_appointment'),
]

hospsys/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('appointments/', include('appointments.urls')),
    path('video_chat/', include('video_chat.urls')),
    path("__reload__/", include("django_browser_reload.urls")),
     path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='accounts/password/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password/password_reset_confirm.html'), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password/password_reset_complete.html'), name='password_reset_complete'), 

]

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import User, DoctorAvailability, WorkingShift, DoctorProfile, PatientProfile,Department
from django import forms
from django.forms import ModelForm, fields
import datetime as dt
from entangled.forms import EntangledModelForm
from cloudinary.forms import CloudinaryFileField


class RegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['email', 'username','first_name', 'middle_name', 'last_name','user_type']

DAY_CHOICES = (
        ('sunday', 'Sunday'),
        ('monday', 'Monday'),
        ('tuesday', 'Tuesday'),
        ('wednesday', 'Wednesday'),
        ('thursday', 'Thursday'),
        ('friday', 'Friday'),
        ('saturday', 'Saturday'),
    )
HOUR_CHOICES = [(dt.time(hour=x), '{:02d}:00'.format(x)) for x in range(0, 24)]

# class DoctorAvailabilityForm(forms.Form):
#     available_days = forms.MultipleChoiceField(widget=forms.CheckboxSelectMultiple(), choices = DAY_CHOICES)
#     available_start_time = forms.ChoiceField(widget=forms.Select(), choices = HOUR_CHOICES)
#     available_end_time = forms.ChoiceField(widget=forms.Select(), choices = HOUR_CHOICES)

# class DoctorAvailabilityForm(EntangledModelForm):
#     days= fields.MultipleChoiceField(widget=forms.CheckboxSelectMultiple(), choices=DAY_CHOICES)
#     start_time = fields.ChoiceField(choices = HOUR_CHOICES)
#     end_time = fields.ChoiceField(choices = HOUR_CHOICES)

#     class Meta:
#         model = DoctorAvailability
#         entangled_fields = {'working_shifts': ['days', 'start_time', 'end_time']}
#         untangled_fields = ['doctor','available_status']
#         exclude = ['doctor','available_status']

class RegistrationProfileForm(forms.ModelForm):
    class Meta:
        model = DoctorProfile
        fields = ['department', 'nmc']

class DoctorWorkingShiftForm(forms.Form):
    working_day = forms.ChoiceField(widget=forms.Select(attrs={'style': 'width: 200px;padding: 8px; margin-right: 16px;'}), choices = DAY_CHOICES)
    start_time = forms.ChoiceField(widget=forms.Select(attrs={'style': 'width: 200px;padding: 8px; margin-right: 16px;'}), choices = HOUR_CHOICES)
    end_time = forms.ChoiceField(widget=forms.Select(attrs={'style': 'width: 200px;padding: 8px; margin-right: 16px;'}), choices = HOUR_CHOICES)
    
    # class Meta:
    #     model = WorkingShift
    #     exclude = ['doctor_profile']
    #     widget = {
    #         'start_time': forms.MultipleChoiceField(widget=forms.CheckboxSelectMultiple(), choices = DAY_CHOICES)
    #     }

class UpdateUserForm(forms.ModelForm):
    profile_image = CloudinaryFileField(label=False,
        options = {
            'crop': 'thumb',
            'width': 500,
            'height': 500,
            'folder': 'hospsys_profile'
       },
       widget=forms.FileInput(attrs={'style':'width: 300px; padding: auto; display:none;', 'id':'profile_image_upload'}),
    )
    class Meta:
        model = User
        fields = ['profile_image','email', 'username', 'first_name','middle_name','last_name']

class PatientProfileForm(forms.ModelForm):
    class Meta:
        model = PatientProfile
        fields = ['address_street', 'address_city']

class DoctorProfileForm(forms.ModelForm):
    class Meta:
        model = DoctorProfile
        fields = ['department', 'nmc']

accounts/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from .forms import RegistrationForm, DoctorWorkingShiftForm, RegistrationProfileForm, UpdateUserForm, PatientProfileForm, DoctorProfileForm
from django.urls import reverse
from .models import DoctorAvailability, DoctorProfile, WorkingShift, User
from django.views.generic.edit import UpdateView
from appointments.models import Appointment
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.core.mail import EmailMessage, send_mail, BadHeaderError
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.contrib.auth.tokens import default_token_generator
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import PasswordResetForm
from django.db.models.query_utils import Q

# Create your views here.
def index(request):
    return HttpResponse("index page.")

def register(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()
            token = default_token_generator.make_token(user)
            current_site = get_current_site(request)
            mail_subject = 'Activate your account.'
            message = render_to_string('registration/activation_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid':urlsafe_base64_encode(force_bytes(user.pk)),
                'token': token,
            })
            to_email = form.cleaned_data.get('email')
            email = EmailMessage(
                        mail_subject, message, to=[to_email]
            )
            email.send()
            messages.success(request,'Please verify your account before logging in.')
            return HttpResponseRedirect(reverse('accounts:login'))
    else:
        form = RegistrationForm()
    return render(request, 'registration/register.html', {'form': form})

def register_profile(request, user):
    if request.method == 'POST':
        pass
    else:
        form = RegistrationProfileForm()
    return render(request, 'registration/register_profile.html', {'form': form})

def activate(request, uidb64, token):
    try:
        uid = urlsafe_base64_decode(uidb64)
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and default_token_generator.check_token(user, token):
        user.is_active = True
        user.save()
        # login(request, user)
        # return redirect('home')
        messages.success(request,'Account verified. You can login now.')
        return HttpResponseRedirect(reverse('accounts:login'))
    else:
        return HttpResponse('Activation link is invalid!')

def password_reset_request(request):
	if request.method == "POST":
		password_reset_form = PasswordResetForm(request.POST)
		if password_reset_form.is_valid():
			data = password_reset_form.cleaned_data['email']
			associated_users = User.objects.filter(Q(email=data))
			if associated_users.exists():
				for user in associated_users:
					subject = "Password Reset Requested"
					email_template_name = "accounts/password/password_reset_email.txt"
					c = {
					"email":user.email,
					'domain': get_current_site(request).domain,
					'site_name': 'HospSys',
					"uid": urlsafe_base64_encode(force_bytes(user.pk)),
					"user": user,
					'token': default_token_generator.make_token(user),
					'protocol': 'http',
					}
					email = render_to_string(email_template_name, c)
					try:
						send_mail(subject, email, 'admin@admin.com' , [user.email], fail_silently=False)
					except BadHeaderError:
						return HttpResponse('Invalid header found.')
					return redirect ("/password_reset/done/")
	password_reset_form = PasswordResetForm()
	return render(request=request, template_name="accounts/password/password_reset.html", context={"password_reset_form":password_reset_form})

@login_required
def dashboard(request):
    if request.user.is_authenticated:
        user = request.user
        if user.is_doctor:
            working_shifts_form = DoctorWorkingShiftForm()
            appointments = Appointment.objects.filter(doctor = user)
            context = {
                'current_user': user,
                'working_shifts_form': working_shifts_form,
                'appointments': appointments,
            }
            return render(request, 'accounts/doctor_dashboard.html', context)
        elif user.is_patient:
            appointments = Appointment.objects.filter(patient = user, approval_status__in = ['pending', 'approved'])
            context = {
                'current_user': user,
                'appointments': appointments,
            }
            return render(request, 'accounts/patient_dashboard.html', context)
        else:
            return HttpResponseRedirect(reverse('accounts:login'))
    else:
        return HttpResponseRedirect(reverse('accounts:login'))

@login_required
def profile(request, user_id):
    if request.method == 'POST':
        userform = UpdateUserForm(request.POST, request.FILES, instance=request.user)
        if request.user.user_type == 'patient':
            profileform = PatientProfileForm(request.POST, instance=request.user.patientprofile)
        else:
            profileform = DoctorProfileForm(request.POST, instance=request.user.doctorprofile)
        if userform.is_valid() and profileform.is_valid():
            userform.save()
            profileform.save()
            messages.success(request,"Profile successfully updated.")
            return redirect('accounts:profile', user_id=request.user.id)
    else:
        userform = UpdateUserForm(instance=request.user)
        if request.user.user_type == 'patient':
            profileform = PatientProfileForm(instance=request.user.patientprofile)
        else:
            profileform = DoctorProfileForm(instance=request.user.doctorprofile)


        context = {
            'userform': userform,
            'profileform': profileform,
        }
        return render(request, 'accounts/profile.html', context)
        
@login_required
def view_working_shifts(request):
    if request.user.is_authenticated:
        if request.user.user_type == 'doctor':
            working_shifts = WorkingShift.objects.filter(doctor_profile = request.user.doctorprofile)
            return render(request, 'accounts/view_availability.html', {'working_shifts': working_shifts})
        else:
            return HttpResponseRedirect(reverse('accounts:dashboard'))
    

# def change_availability(request):
#     if request.method == 'POST':
#         form = DoctorAvailabilityForm(request.POST)
#         available_days = []

#         if form.is_valid():
#             av_days = form.cleaned_data['available_days']
#             for av_day in av_days:
#                 available_days.append(av_day) 
#             available_start_time = form.cleaned_data['available_start_time']
#             available_end_time = form.cleaned_data['available_end_time']
#             doctor = request.user.doctorprofile
#             available_status = 'offline'
#             dav = DoctorAvailability.objects.filter(doctor=request.user.doctorprofile).update(available_days=available_days, available_start_time=available_start_time, available_end_time=available_end_time, available_status=available_status, doctor=doctor)
#             # dav_update = dav.update(available_days=available_days, available_start_time=available_start_time, available_end_time=available_end_time, available_status=available_status, doctor=doctor)
#             return HttpResponseRedirect(reverse('accounts:dashboard'))
#             # if da.update_or_create():
#             #     return HttpResponseRedirect(reverse('accounts:dashboard'))
#             # else:
#             #     return render(request, 'accounts/change_availability.html', {'form': form})            
#     else:
#         # doctorprofile = DoctorProfile.objects.get(doctor=request.user)
#         # dav = doctorprofile.doctoravailability
#         # av_days = dav.available_days
#         # av_start_time = dav.available_start_time
#         # av_end_time = dav.available_end_time
#         # av_status = dav.available_status
#         # data = {
#         #     'available_days': av_days,
#         #     'available_start_time': av_start_time,
#         #     'available_end_time': av_end_time,
#         #     'available_status': av_status,
#         #     'doctor': request.user
#         # }
#         # working_shifts = DoctorAvailability.objects.filter(doctor=request.user.doctorprofile).values('working_shifts')        
#         form = DoctorAvailabilityForm()
#     return render(request, 'accounts/change_availability.html', {'form': form})

@login_required
def edit_working_shifts(request):
    if request.user.is_authenticated:
        if request.user.user_type == 'doctor':
            if request.method == 'POST':
                form = DoctorWorkingShiftForm(request.POST)

                if form.is_valid():
                    doctor_profile = request.user.doctorprofile
                    working_day = form.cleaned_data['working_day']
                    start_time = form.cleaned_data['start_time']
                    end_time = form.cleaned_data['end_time']
                    obj, created = WorkingShift.objects.update_or_create(doctor_profile=doctor_profile, working_day=working_day, defaults = {'start_time':start_time, 'end_time': end_time})
                    # obj = form.save(commit=False)
                    # obj.doctor_profile = doctor_profile
                    # obj.save()
                    if obj:

accounts/templates/accounts/layouts/sidebar_menu.html
{% if request.user.is_doctor %}
<!-- Sidebar Menu -->
<nav class="mt-2">
<ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
  <li class="nav-item">
    <a href="{% url 'accounts:dashboard' %}" class="nav-link">
      <i class="nav-icon far fa-image"></i>
      <p>
        Dashboard
      </p>
    </a>
</li>
{% if current_user.doctorprofile.is_nmc_verified %}
<li class="nav-item">
    <a href="{% url 'accounts:edit_working_shifts' %}" class="nav-link">
      <i class="nav-icon far fa-image"></i>
      <p>
        View/Edit Working Hours
      </p>
    </a>
</li>
{% endif %}
</ul>
</nav>
<!-- /.sidebar-menu -->
{% endif %}


{% if request.user.is_patient %}
<nav class="mt-2">
    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
      <li class="nav-item">
        <a href="{% url 'accounts:dashboard' %}" class="nav-link">
          <i class="nav-icon far fa-image"></i>
          <p>
            Dashboard
          </p>
        </a>
    </li>
      <li class="nav-item">
        <a href="{% url 'appointments:list_doctors' %}" class="nav-link">
          <i class="nav-icon far fa-image"></i>
          <p>
            Create Appointments
          </p>
        </a>
      </li>

      <li class="nav-item">
        <a href="{% url 'appointments:doctor_availability' %}" class="nav-link">
          <i class="nav-icon far fa-image"></i>
          <p>
            Check Doctor Availablility
          </p>
        </a>
      </li>
           
    </ul>
    </nav>
{% endif %}

accounts/templates/accounts/layouts/starter.html
<!DOCTYPE html>
<!--
This is a starter template page. Use this page to start your new project from
scratch. This page gets rid of all links and provides the needed markup only.
-->
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{% block title %} {% endblock %}</title>
  {% load static %}
  {% load cloudinary %} 
  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome Icons -->
  <link rel="stylesheet" href="{% static 'accounts/adminlte_plugins/fontawesome-free/css/all.min.css'%}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'accounts/adminlte_dist/css/adminlte.min.css'%}">

  <link rel="stylesheet" href="{% static 'accounts/css/style.css' %}">
</head>
<body class="hold-transition sidebar-mini">
<div class="wrapper">

  <!-- Navbar -->
  <nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="{% url 'accounts:dashboard' %}" class="nav-link">Home</a>
      </li>
      <!-- <li class="nav-item d-none d-sm-inline-block">
        <a href="#" class="nav-link">Contact</a>
      </li> -->
    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
 
      <!-- <li class="nav-item">
        <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#" role="button">
          <i class="fas fa-th-large"></i>
        </a>
      </li> -->
      <li class="nav-item">
        <a class="nav-link btn btn-danger text-light" href="{% url 'accounts:logout' %}">Logout</a>
      </li>
    </ul>
  </nav>
  <!-- /.navbar -->

  <!-- Main Sidebar Container -->
  <aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="{% url 'accounts:dashboard' %}" class="brand-link">
      <img src="{% static 'accounts/images/logo_200x200.png'%}" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
      <span class="brand-text font-weight-light">HospSys Dashboard</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user panel (optional) -->
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
          <img src="{{ request.user.profile_image.url }}" class="img-circle elevation-2" alt="User Image">
        </div>
        <div class="info">
          <a href="{% url 'accounts:profile' request.user.id %}" class="d-block">{{ request.user.get_full_name.title }}</a>
        </div>
      </div>

      <!-- SidebarSearch Form -->
      <div class="form-inline">
        <div class="input-group" data-widget="sidebar-search">
          <input class="form-control form-control-sidebar" type="search" placeholder="Search" aria-label="Search">
          <div class="input-group-append">
            <button class="btn btn-sidebar">
              <i class="fas fa-search fa-fw"></i>
            </button>
          </div>
        </div>
      </div>
      
      {% include 'accounts/layouts/sidebar_menu.html' %}
  

    </div>
    <!-- /.sidebar -->
  </aside>
  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">

        {% block content %}

        {% endblock content %}
      </div>
    </div>
  </div>
  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
    <div class="p-3">
      <h5>Title</h5>
      <p>Sidebar content</p>
    </div>
  </aside>
  <!-- /.control-sidebar -->

  <!-- Main Footer -->
  <footer class="main-footer">
  
    <!-- Default to the left -->
    <strong>Copyright &copy; 2022 <a href="#">HospSys</a>.</strong> All rights reserved.
  </footer>
</div>
<!-- ./wrapper -->

<!-- REQUIRED SCRIPTS -->

<!-- jQuery -->
<script src="{% static 'accounts/adminlte_plugins/jquery/jquery.min.js'%}"></script>
<!-- Bootstrap 4 -->
<script src="{% static 'accounts/adminlte_plugins/bootstrap/js/bootstrap.bundle.min.js'%}"></script>
<!-- AdminLTE App -->
<script src="{% static 'accounts/adminlte_dist/js/adminlte.min.js'%}"></script>

</body>
</html>